# -*- coding: utf-8 -*-
"""mk2436_final_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OhX1EzTbj68yVWUteveSwe8E_0OQCWgD

## Data Mining Final Project

## Mihir Kadam
Ucid: mk2436
<br>Email Id: mk2436@njit.edu

##Submitted to: Dr. Yasser Abduallah
<br>
<br>

**Goal:**  
I have used the UCI Credit Approval Dataset. The goal of this project is to implement **3 Machine Learning Algorithms** — Random Forest, SVM, and Conv1D — and perform **binary classification** to determine, based on the available features, if a person will be **approved** for a credit card or **denied**.
<br>
<br>
<br>
**Model Selection**:
<br>
Random Forest was Mandatory Implementation.
I have decided to use SVM (Tradtional ML model) and Conv1D (Deep Learning Model) since they are one of the models with least model complextiy in their categories. This is crucial for a small dataset since less model complexity means the gap between out of sample error and in-sample error is minimal. This means that the model is better at generalization.

1. Installing all the dependenceies
"""

# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

# sklearn - model selection
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold

# sklearn - preprocessing
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# sklearn - feature selection
from sklearn.feature_selection import mutual_info_classif

# sklearn - models
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

# sklearn - metrics
from sklearn.metrics import classification_report, accuracy_score, roc_curve, auc, confusion_matrix, roc_auc_score, brier_score_loss

# imbalance handling
from imblearn.over_sampling import SMOTE

# TensorFlow / Keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, GlobalAveragePooling1D, Dense, Dropout, BatchNormalization, Flatten
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras import regularizers


"""2. Reading the data set and verifying its contents"""

# Reading the data from a csv file and loading it in a pandas framework
data = pd.read_csv(f'clean_dataset.csv', header=0)
print(data.head())

# Printing data info
data.info()

# Printing data description
data.describe()

"""3. Removing the target feature from X and assigning it to y as the target variable"""

# Dropping the Target feature from X
X = data.drop('Approved', axis=1)

# Configuring y as the Target feature
y = data['Approved']

"""## 4. Data Visualization

4.1. Calculating the Correlation Matrix
"""

# Calculating the correlation matrix
correlation_matrix = X.corr(numeric_only=True)

# Plotting the Correalation Heatmap
# This will be used to drop highly correlated features
plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Correlation Matrix of Features')
plt.show(block=False)
plt.pause(0.001)

"""The heatmap above displays the correlation matrix for the numerical features in the dataset. Each cell in the heatmap shows the correlation coefficient between two features.

*   **Values close to 1** indicate a strong positive correlation (as one feature increases, the other tends to increase).
*   **Values close to -1** indicate a strong negative correlation (as one feature increases, the other tends to decrease).
*   **Values close to 0** indicate a weak or no linear correlation.
________________________________________________________________________

4.2. Plotting the Histograms for all the features
"""

# Plotting histogram for all the features
X.hist(bins=50, figsize=(10, 10))
plt.show(block=False)
plt.pause(0.001)

"""4.3. Plotting PairPlot for all the features"""

# Plotting pairplot for the features
sns.pairplot(data, hue='Approved')
plt.show(block=False)
plt.pause(0.001)

"""## 5. Data Preprocessing
5.1 Dropping highly correlated features
From the Heatmap above we can see that **'BankCustomer'** and **'Married'** features are highly correlated. So I have decided to drop them. Doing this helped in improving overall model performances.
"""

# Dropping the highly correlated features(>0.80)
# This improved the model performances by almost 3-5%
X = X.drop('BankCustomer', axis=1)
X = X.drop('Married', axis=1)

"""5.2 Checking for missing values

I have checked the data for missing values. Since there are no missing values nothing was done to handle missing values.
"""

# Checking for missing values
missing_values = X.isnull().sum()
print("Missing values in each column:\n", missing_values)

"""5.3 Checking Class Distribution

Here I monitor the class distribution for the target feature **"Approved"**. Since the data has some class imbalance. I have applied SMOTE to generate synthetic data to balance the classes.
"""

# Monitoring the class distribution to look for any imbalance
class_distribution = data['Approved'].value_counts()

print(class_distribution)

# Plotting class imbalance
plt.figure(figsize=(6, 5))
ax = sns.barplot(x=class_distribution.index, y=class_distribution.values, palette='viridis')
plt.title('Class Distribution of Approved Feature')
plt.xlabel('Approval Status')
plt.ylabel('Number of Applicants')
plt.xticks([0, 1], ['Not Approved', 'Approved'])

# Add numbers on bars
for i, v in enumerate(class_distribution.values):
    plt.text(i, v + 5, str(v), ha='center', fontweight='bold')

plt.show(block=False)
plt.pause(0.001)

"""5.4 Splitting the data in Training and Testing sets"""

# Splitting the data in Training and Testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""5.5 Applying One Hot Encoding

Since the dataset contains manay categorical features, I have applied One Hot encoding to convert them into numerical values
"""

# Identifying the categorical columns
categorical_cols = X_train.select_dtypes(include=['object', 'category']).columns

# One-hot encoding categorical columns
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols)
    ],
    remainder='passthrough'  # keep numerical columns as it is
)

# Apply preprocessing
X_train_encoded = preprocessor.fit_transform(X_train)
X_test_encoded = preprocessor.transform(X_test)

"""5.6 Normalizing the Dataset

Using **StandardScaler** I have normalized the data. This has helped in improving the model performance significantly.
"""

# Normalizing the Dataset
# Helper improve accuracy by 3-5%

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit the scaler on the training data and transform both training and test data
X_train_normalized = scaler.fit_transform(X_train_encoded)
X_test_normalized = scaler.transform(X_test_encoded)

# Printing results of normalization
print("Shape of X_train_normalized:", X_train_normalized.shape)
print("Shape of X_test_normalized:", X_test_normalized.shape)

print("\nMean of first 5 features in X_train_normalized:", X_train_normalized[:, :5].mean(axis=0))
print("Standard Deviation of first 5 features in X_train_normalized:", X_train_normalized[:, :5].std(axis=0))

# Printing all the feature names after one-hot encoding
preprocessor.get_feature_names_out()

# Computing the mutual information between each feature and the target variable
mutual_info = mutual_info_classif(X_train_encoded, y_train)
feature_names = preprocessor.get_feature_names_out()

# Printing feature and it's mutual information value
print(list(zip(feature_names, mutual_info)))

# Apply SMOTE to the training data
smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train_normalized, y_train)

print(f"Original training set shape: {X_train_normalized.shape, y_train.shape}")
print(f"SMOTE training set shape: {X_train_smote.shape, y_train_smote.shape}")
print("Class distribution after SMOTE:\n", y_train_smote.value_counts())

"""## 6. Training and Testing Models

6.1 Performing Grid Search for Random Forest Classifier to find the best model and the best parameters for my dataset. Grid Search will explore multiple parameters and pick the best performing model.
"""

# Defining parameter grid
rf_param_grid = {
    'n_estimators': [70, 80, 90, 100],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 4, 6, 8, 10],
    'min_samples_leaf': [1, 2],
    'bootstrap': [True]
}


# Initializing base model
rf_base_model = RandomForestClassifier(random_state=42)

# Performing Grid search
grid_search = GridSearchCV(
    estimator=rf_base_model,
    param_grid=rf_param_grid,
    cv=3,
    scoring='accuracy'
)

# Fit on training data
grid_search.fit(X_train_smote, y_train_smote)

# Best model
best_rf_model = grid_search.best_estimator_

# Best parameters
best_rf_params = grid_search.best_params_

print("Best Parameters for Random Forest:")
print(f"n_estimators: {best_rf_params['n_estimators']}")
print(f"max_depth: {best_rf_params['max_depth']}")
print(f"min_samples_split: {best_rf_params['min_samples_split']}")
print(f"min_samples_leaf: {best_rf_params['min_samples_leaf']}")
print(f"boostrap: {best_rf_params['bootstrap']}")

"""6.2 Performing Grid Search for Support Vector Machine to find the best model and the best parameters for my dataset. Grid Search will explore multiple parameters and pick the best performing model."""

# Defining parameter grid
svm_param_grid = {
    'C': [0.01, 0.1, 0.5, 1],
    'kernel': ['linear'],
}

# Initializing base model
svm_base_model = SVC(probability=True,random_state=42)

# Performing Grid search
grid_search = GridSearchCV(
    estimator=svm_base_model,
    param_grid=svm_param_grid,
    cv=3,
    scoring='accuracy')

# Fit on training data
grid_search.fit(X_train_smote, y_train_smote)

# Best model
svm_best_model = grid_search.best_estimator_

# Best parameters
svm_best_params = grid_search.best_params_

print("Best Parameters for SVM:")
print(f"C: {svm_best_params['C']}")
print(f"kernel: {svm_best_params['kernel']}")

"""
6.3 Defining the Conv1D model

Here we define the configuration for Conv1D model. I have decided use multiple layers using different configuration to ensure efficient model performance.

I have also implemented L2 regularization because the model was overfitting during the 10-Fold Cross validation. Regularization helped reducing over overfitting."""

# Defining the Conv1D model
# Adding L2 regularization helped reduce overfitting
conv1d_model = Sequential([
    Conv1D(
        filters=32,
        kernel_size=3,
        activation='relu',
        kernel_regularizer=regularizers.l2(0.003)  # L2 regularization
    ),
    Conv1D(
        filters=64,
        kernel_size=3,
        activation='relu',
        kernel_regularizer=regularizers.l2(0.002)
    ),
    Flatten(),
    Dense(64, activation='relu', kernel_regularizer=regularizers.l2(0.001)),
    Dropout(0.5),
    Dense(1, activation='sigmoid')
])

# Compiling Conv1D model
conv1d_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

"""6.4 Defining Helper Functions

These helper functions run the models defined earlier using subset of the training set. This will be used during the 10-Fold Cross Validation.

Additional Helper function is created to Plot the ROC curves for each fold and calculate a series of metrics, respectively.
"""

def helper_RandomForestClassifier(X_train_parameter, X_test_parameter, y_train_parameter, y_test_parameter):

  # Takes the input dataset and trains the Best Random Forest Model
  best_rf_model.fit(X_train_parameter, y_train_parameter)

  # Testing the model
  y_pred_rf = best_rf_model.predict(X_test_parameter)

  # Probabilities for ROC curve
  y_prob = best_rf_model.predict_proba(X_test_parameter)[:, 1]

  return y_prob

def helper_SVM(X_train_parameter, X_test_parameter, y_train_parameter, y_test_parameter):

  # Takes the input dataset and trains the Best SVM Model
  svm_best_model.fit(X_train_parameter, y_train_parameter)

  # Testing the model
  y_pred_svm = svm_best_model.predict(X_test_parameter)

  # Probabilities for ROC curve
  y_pred_svm_proba = svm_best_model.predict_proba(X_test_parameter)[:, 1]

  return y_pred_svm_proba

def helper_Conv1D(X_train_parameter, X_test_parameter, y_train_parameter, y_test_parameter):

  # Adding Early Stop to the NN
  early_stop = EarlyStopping(
      monitor='loss',
      patience=3,
      restore_best_weights=True
  )

  # Train the model
  history = conv1d_model.fit(
      X_train_parameter,
      y_train_parameter,
      epochs=20,
      callbacks=[early_stop],
      batch_size=32,
      verbose=0
      )

  # Evaluate the model on the test set
  loss, accuracy = conv1d_model.evaluate(X_test_parameter, y_test_parameter, verbose=0)

  # Make predictions and calculate Probabilities for ROC curve
  y_pred_conv1d_proba = conv1d_model.predict(X_test_parameter, verbose=0)
  y_pred_conv1d = (y_pred_conv1d_proba > 0.5).astype(int)

  return y_pred_conv1d_proba

# Helper function that helps plot the ROC curves for all the flods
def plot_roc_curve(ax, model, y_test_parameter, y_prob_parameter):
  fpr, tpr, thresholds = roc_curve(y_test_parameter, y_prob_parameter)
  roc_auc = auc(fpr, tpr)
  ax.plot(fpr, tpr, linewidth=2, label=f"AUC = {roc_auc:.2f}")
  ax.plot([0, 1], [0, 1], linestyle="--")
  ax.set_xlabel("False Positive Rate")
  ax.set_ylabel("True Positive Rate")
  ax.set_title(f"ROC Curve {model}")
  ax.legend(loc="lower right")
  ax.grid()
  return ax

def compute_all_metrics(y_true, y_prob, y_pred=None):
    # If y_pred not provided, threshold 0.5
    if y_pred is None:
        y_pred = (y_prob >= 0.5).astype(int)

    # Confusion matrix
    cm = confusion_matrix(y_true, y_pred)  # [[TN, FP],[FN, TP]]
    TN, FP = cm[0]
    FN, TP = cm[1]

    # Basic metrics
    TPR = TP / (TP + FN) if (TP + FN) != 0 else 0  # Recall / Sensitivity
    TNR = TN / (TN + FP) if (TN + FP) != 0 else 0  # Specificity
    FPR = FP / (TN + FP) if (TN + FP) != 0 else 0
    FNR = FN / (TP + FN) if (TP + FN) != 0 else 0
    Precision = TP / (TP + FP) if (TP + FP) != 0 else 0
    F1_measure = 2 * TP / (2 * TP + FP + FN) if (2 * TP + FP + FN) != 0 else 0
    Accuracy = (TP + TN) / (TP + FP + FN + TN)
    Error_rate = (FP + FN) / (TP + FP + FN + TN)
    BACC = (TPR + TNR)/2
    TSS = TPR - FPR
    HSS = 2*(TP*TN - FP*FN)/((TP+FN)*(FN+TN) + (TP+FP)*(FP+TN)) if ((TP+FN)*(FN+TN) + (TP+FP)*(FP+TN)) != 0 else 0

    # Probabilistic metrics
    BS = brier_score_loss(y_true, y_prob)
    AUC = roc_auc_score(y_true, y_prob)

    return {
        'TP': TP, 'TN': TN, 'FP': FP, 'FN': FN,
        'TPR': TPR, 'TNR': TNR, 'FPR': FPR, 'FNR': FNR,
        'Precision': Precision, 'F1_measure': F1_measure,
        'Accuracy': Accuracy, 'Error_rate': Error_rate,
        'BACC': BACC, 'TSS': TSS, 'HSS': HSS,
        'Brier_score': BS, 'AUC': AUC
    }

"""6.5 Performing 10-Fold Corss Validation for all 3 models"""

# Initialize 10-fold cross-validator
skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

# Store all metrics
rf_metrics_list = []
svm_metrics_list = []
conv1d_metrics_list = []

# Loop through each fold
for fold, (train_idx, val_idx) in enumerate(skf.split(X_train_smote, y_train_smote), start=1):

    # Split SMOTE data using numpy indexing
    X_fold_train = X_train_smote[train_idx]
    X_fold_val   = X_train_smote[val_idx]
    y_fold_train = y_train_smote[train_idx]
    y_fold_val   = y_train_smote[val_idx]

    rf_y_prob = helper_RandomForestClassifier(X_fold_train, X_fold_val, y_fold_train, y_fold_val)
    rf_metrics = compute_all_metrics(y_fold_val, rf_y_prob)
    rf_metrics['Fold'] = fold
    rf_metrics_list.append(rf_metrics)

    svm_y_prob = helper_SVM(X_fold_train, X_fold_val, y_fold_train, y_fold_val)
    svm_metrics = compute_all_metrics(y_fold_val, svm_y_prob)
    svm_metrics['Fold'] = fold
    svm_metrics_list.append(svm_metrics)

    X_fold_train_cnn = X_fold_train.reshape(X_fold_train.shape[0], X_fold_train.shape[1], 1)
    X_fold_val_cnn   = X_fold_val.reshape(X_fold_val.shape[0], X_fold_val.shape[1], 1)
    conv1d_y_prob = helper_Conv1D(X_fold_train_cnn, X_fold_val_cnn, y_fold_train, y_fold_val)
    conv_metrics = compute_all_metrics(y_fold_val, conv1d_y_prob)
    conv_metrics['Fold'] = fold
    conv1d_metrics_list.append(conv_metrics)


    metrics_names = list(rf_metrics.keys())
    print(f"----Metrics for all Algorithms in Fold {fold}----")
    print("Metric      RF     SVM    Conv1D")

    for m in metrics_names:
        rf_val = f"{rf_metrics[m]:.2f}"
        svm_val = f"{svm_metrics[m]:.2f}"
        conv_val = f"{conv_metrics[m]:.2f}"
        print(f"{m:<12} {rf_val:<6} {svm_val:<6} {conv_val:<6}")

    fig, axes = plt.subplots(1, 3, figsize=(10, 3))

    plot_roc_curve(axes[0], f"Random Forest fold:{fold}", y_fold_val, rf_y_prob)
    plot_roc_curve(axes[2], f"SVM fold:{fold}", y_fold_val, svm_y_prob)
    plot_roc_curve(axes[1], f"Conv1D fold:{fold}", y_fold_val, conv1d_y_prob)

    plt.tight_layout()
    plt.show(block=False)
    plt.pause(0.001)

    print("\n\n")


rf_df = pd.DataFrame(rf_metrics_list)
svm_df = pd.DataFrame(svm_metrics_list)
conv1d_df = pd.DataFrame(conv1d_metrics_list)

"""6.6 Printing Average of all metrics for all 3 models and plotting the overall ROC curve for the training data"""

# Printing Average of all Metrics for Random Forest
print("\nRandom Forest average over 10 folds metrics:")
print(rf_df.mean(numeric_only=True))

# Printing Average of all Metrics for SVM
print("\nSVM average over 10 folds metrics:")
print(svm_df.mean(numeric_only=True))

# Printing Average of all Metrics for Conv1D
print("\nConv1D average over 10 folds metrics:")
print(conv1d_df.mean(numeric_only=True))

# Calculating ROC curve for the entire Data
rf_final_y_prob = helper_RandomForestClassifier(
    X_train_smote,          # full SMOTE training features
    X_test_normalized,      # your untouched test set (normalized)
    y_train_smote,          # full SMOTE training labels
    y_test                  # true test labels
)

fpr, tpr, thresholds = roc_curve(y_test, rf_final_y_prob)
roc_auc = auc(fpr, tpr)
print("ROC Curve for entire data for Random Forest:")
plt.figure(figsize=(8,6))
plt.plot(fpr, tpr, linewidth=2, label=f"AUC = {roc_auc:.2f}")
plt.plot([0, 1], [0, 1], linestyle="--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("Random Forest ROC Curve")
plt.legend(loc="lower right")
plt.grid()
plt.show(block=False)
plt.pause(0.001)

# Calculating ROC curve for the entire Data

# Reshaping the data for Conv1D
X_train_smote_reshaped = X_train_smote.reshape(X_train_smote.shape[0], X_train_smote.shape[1], 1)
X_test_normalized_reshaped = X_test_normalized.reshape(X_test_normalized.shape[0], X_test_normalized.shape[1], 1)

final_y_pred_conv1d_proba = helper_Conv1D(
    X_train_smote_reshaped,
    X_test_normalized_reshaped,
    y_train_smote,
    y_test
    )

# Compute ROC curve
fpr, tpr, thresholds = roc_curve(y_test, final_y_pred_conv1d_proba)
roc_auc = auc(fpr, tpr)

print("ROC Curve for the entire Data for Conv1D:")
plt.figure(figsize=(8,6))
plt.plot(fpr, tpr, linewidth=2, label=f"AUC = {roc_auc:.2f}")
plt.plot([0, 1], [0, 1], linestyle="--", color='gray')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("Conv1D ROC Curve")
plt.legend(loc="lower right")
plt.grid()
plt.show(block=False)
plt.pause(0.001)

# Calculating ROC curve for the entire Data
svm_final_y_prob = helper_SVM(
    X_train_smote,          # full SMOTE training features
    X_test_normalized,      # your untouched test set (normalized)
    y_train_smote,          # full SMOTE training labels
    y_test                  # true test labels
)

fpr, tpr, thresholds = roc_curve(y_test, svm_final_y_prob)
roc_auc = auc(fpr, tpr)
print("ROC Curve for the entire Data for SVM:")
plt.figure(figsize=(8,6))
plt.plot(fpr, tpr, linewidth=2, label=f"AUC = {roc_auc:.2f}")
plt.plot([0, 1], [0, 1], linestyle="--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve SVM")
plt.legend(loc="lower right")
plt.grid()
plt.show(block=False)
plt.pause(0.001)

"""6.7 Displaying Overall performance of all the 3 algorithms per fold"""

print("Metrics of Random Forest Across All iterations:\n")
rf_df_indexed = rf_df.set_index('Fold')
rf_transposed = rf_df_indexed.T
metric_col_width = 12
value_col_width = 8
header = f"{'Metric':<{metric_col_width}}" + "".join(f"{f'Iter{i+1}':>{value_col_width}}" for i in range(rf_transposed.shape[1]))
print(header)
print("-" * (metric_col_width + rf_transposed.shape[1]*value_col_width))
for metric in rf_transposed.index:
    row_values = [f"{v:>{value_col_width}.2f}" for v in rf_transposed.loc[metric]]
    print(f"{metric:<{metric_col_width}}" + "".join(row_values))

print("Metrics of SVM Across All iterations:\n")
svm_df_indexed = svm_df.set_index('Fold')
svm_transposed = svm_df_indexed.T
metric_col_width = 12
value_col_width = 8
header = f"{'Metric':<{metric_col_width}}" + "".join(f"{f'Iter{i+1}':>{value_col_width}}" for i in range(svm_transposed.shape[1]))
print(header)
print("-" * (metric_col_width + svm_transposed.shape[1]*value_col_width))
for metric in svm_transposed.index:
    row_values = [f"{v:>{value_col_width}.2f}" for v in svm_transposed.loc[metric]]
    print(f"{metric:<{metric_col_width}}" + "".join(row_values))

print("Metrics of Conv1D Across All iterations:\n")
conv1d_df_indexed =  conv1d_df.set_index('Fold')
conv1d_transposed =  conv1d_df_indexed.T
metric_col_width = 12
value_col_width = 8
header = f"{'Metric':<{metric_col_width}}" + "".join(f"{f'Iter{i+1}':>{value_col_width}}" for i in range( conv1d_transposed.shape[1]))
print(header)
print("-" * (metric_col_width +  conv1d_transposed.shape[1]*value_col_width))
for metric in  conv1d_transposed.index:
    row_values = [f"{v:>{value_col_width}.2f}" for v in  conv1d_transposed.loc[metric]]
    print(f"{metric:<{metric_col_width}}" + "".join(row_values))